# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'windows-2019'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- task: ArchiveFiles@2
  inputs: 
    rootFolderOrFile: '$(System.DefaultWorkingDirectory)/ADChildParentForest/ADChildParentForest/DSC'
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/DSC.zip'
    includeRootFolder: false

